name: Publish

on:
  workflow_dispatch:
  push:
      tags:
        - 'v*'

jobs:
  make-framework:
    uses: ./.github/workflows/make-framework.yml

  main:
    runs-on: macOS-latest
    permissions: write-all
    needs: make-framework
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Get release Name
      shell: python
      run: |
        import os
        ref = os.environ['GITHUB_REF']
        name = ref[ref.rfind('/') + 2:]
        with open(os.environ['GITHUB_ENV'], 'w') as env:
          print('RELEASE_NAME=' + name, file=env) 

    - name: Zip Headers
      shell: bash
      run: tar -czf objc-helpers-${{ env.RELEASE_NAME }}.tar.gz include LICENSE VERSION CHANGELOG.md

    - name: Download framework
      uses: actions/download-artifact@v8
      with:
        name: ObjCHelpers-xcframework.zip
        path: '.'

    - name: Package artifacts
      shell: bash
      run: |
        tar -czf objc-helpers-${{ env.RELEASE_NAME }}.tar.gz include LICENSE VERSION CHANGELOG.md
        mv ObjCHelpers-xcframework.zip ObjCHelpers-xcframework-${{ env.RELEASE_NAME }}.zip 

    - name: Make release
      uses: softprops/action-gh-release@v3
      with:
        draft: true
        prerelease: false
        name: ${{ env.RELEASE_NAME }}
        body: ...edit me...
        files: |
          objc-helpers-${{ env.RELEASE_NAME }}.tar.gz
          ObjCHelpers-xcframework-${{ env.RELEASE_NAME }}.zip
  